require("talhaimran.plugins")
require("talhaimran.options")
require("talhaimran.keymaps")
require("talhaimran.mason")
-- require("talhaimran.ufo")
require("talhaimran.treesitter")
require("talhaimran.lsp")
require("talhaimran.cmp")
require("talhaimran.jdtls")
require("talhaimran.nvimtree")
require("talhaimran.comments")
require("talhaimran.neogit")
require("talhaimran.indentline")
require("talhaimran.gitsigns")
require("talhaimran.nvim-tmux-navigator")
require("talhaimran.harpoon")
require("talhaimran.auto-session")
